/* ============================================================
   2Q + BRIDGE — settings, trigger families, states
   ============================================================ */
const STATES=[
 {n:1,key:"position", name:"Positioning",      goal:"Say what you do, briefly, aimed at owners and complex families."},
 {n:2,key:"whynow",   name:"Why now",          goal:"Ask what made it come up now."},
 {n:3,key:"bucket",   name:"Bucket",           goal:"Narrow it to a category, or business vs personal."},
 {n:4,key:"insight",  name:"Pattern insight",  goal:"One line that shows you recognise the situation. No solution."},
 {n:5,key:"bridge",   name:"Coffee bridge",    goal:"Move it out of the room, low pressure, with a timeframe."},
 {n:6,key:"capture",  name:"Contact capture",  goal:"Get the number, the calendar, or a specific next step."}
];

/* Where it happens. Each carries the small talk that starts it.
   window = seconds this setting realistically gives you before they move on. */
const SETTINGS=[
 {id:"sideline", name:"Kids' game sideline", open:["Which one is yours?","How long has yours been playing?"],
  exit:"the game restarting", coffee:"from the sideline", window:120},
 {id:"pickleball", name:"After a pickleball game", open:["Good game. You been playing long?","You from around here?"],
  exit:"the next group waiting on the court", coffee:"than a pickleball conversation", window:120},
 {id:"schoolpickup", name:"School pickup line", open:["You're in the lower school line too?","Which grade?"],
  exit:"the line finally moving", coffee:"than shouting over a carpool line", window:90},
 {id:"forum", name:"YPO forum, before the meeting", open:["You in this chapter long?","What's your business?"],
  exit:"the forum starting", coffee:"than in fifteen minutes before forum", window:150},
 {id:"breakfast", name:"Business association breakfast", open:["Have you been to one of these before?","What business are you in?"],
  exit:"the speaker starting", coffee:"than trying to solve it before the speaker starts", window:120},
 {id:"gala", name:"Charity gala, cocktail hour", open:["How do you know the host?","Have you been involved with this one long?"],
  exit:"dinner being called", coffee:"than in the middle of an event", window:120},
 {id:"golf", name:"Golf outing, waiting on the tee", open:["You play here much?","What do you do when you're not out here?"],
  exit:"their group being called up", coffee:"than standing on a tee box", window:150},
 {id:"yacht", name:"Yacht club, Sunday afternoon", open:["You keep a boat here?","You a member long?"],
  exit:"their family waving them over", coffee:"than out here", window:150},
 {id:"school", name:"School fundraiser", open:["How long have your kids been at the school?","Are you local?"],
  exit:"the auction starting", coffee:"than here", window:120},
 {id:"bbq", name:"Neighbor's backyard barbecue", open:["You're a few streets over, right?","How long have you been in the neighborhood?"],
  exit:"someone calling them over to the grill", coffee:"than over a beer in a backyard", window:150},
 {id:"asado", name:"Family asado, someone's cousin", open:["You're with Nico's side?","You grow up down here?"],
  exit:"the food coming off the grill", coffee:"than in the middle of a family thing", window:150},
 {id:"club", name:"Country club bar", open:["You a member here long?","Are you local, or down for the season?"],
  exit:"their table being ready", coffee:"than at a bar", window:120},
 {id:"mixer", name:"Chamber of commerce mixer", open:["First time at one of these?","What line of work are you in?"],
  exit:"someone pulling them into a photo", coffee:"than in a room like this", window:120},
 {id:"tailgate", name:"UM tailgate", open:["You come to all of them?","You go there, or married into it?"],
  exit:"kickoff", coffee:"than in a parking lot", window:120},
 {id:"lounge", name:"Hospital foundation reception", open:["Are you on the medical side or the board side?","How long have you been involved?"],
  exit:"the program starting", coffee:"than at a hospital function", window:120},
 {id:"wedding", name:"Wedding reception, cocktail hour", open:["Bride or groom?","How do you know them?"],
  exit:"the receiving line forming", coffee:"than at a wedding", window:120},
 {id:"coffeeline", name:"Coffee shop line near the office", open:["You work around here?","Is this your usual spot?"],
  exit:"their order being called", coffee:"than standing in line", window:75},
 {id:"boatshow", name:"Boat show, walking the docks", open:["You shopping or just looking?","You keep one down here?"],
  exit:"their friend catching up to them", coffee:"than walking a dock", window:90}
];

/* Trigger FAMILIES. The specific situation is invented per run by the prospect model;
   these are the taxonomy plus exemplars so it stays in the right lane.
   say/truth/cue are FALLBACK examples only — the model is told to invent its own.
   traps = the questions a real prospect throws that make an advisor break form. */
const TRIGGERS=[
 {id:"cash", family:"Idle cash they have not deployed",
  say:"I've actually been meaning to do something with a bunch of cash that's just sitting there.",
  bucket:"business cash, personal cash, or both",
  buckets:["getting the cash working","reducing taxes","moving money outside the business","just getting organized"],
  truth:"Your CPA mentioned an accumulated earnings problem in the spring and you did nothing about it.",
  seeds:["a CPA warning that went ignored","a large deposit from a one-time event that never got moved",
         "a partner buyout that left cash parked","rates dropping and the money market suddenly paying less"],
  cue:"Yeah, that's exactly what I haven't figured out.",
  jump:"a 401(k), a muni ladder, treasuries, or a donor-advised fund",
  traps:["So what would you actually do with it?","What are you guys getting in this market?","What's your minimum?"]},

 {id:"scattered", family:"No coordination across their financial life",
  say:"Honestly, I probably need to get more organized. Things feel scattered.",
  bucket:"the business side, your personal side, or both",
  buckets:["investments","taxes","estate documents","entities","just not having one clear person"],
  truth:"You could not answer your spouse's question about what you actually have.",
  seeds:["a question from a spouse you could not answer","four custodians and no single statement",
         "an old 401(k) you forgot existed","a bookkeeper who left and took the map with her"],
  cue:"That's exactly it. Nobody's really looking at all of it.",
  jump:"consolidating accounts or a financial plan",
  traps:["Do you do the taxes too?","Isn't that just what my CPA does?","Just send me something and I'll look at it."]},

 {id:"advisor", family:"An incumbent advisor who has gone quiet",
  say:"I've got someone already, but I'm honestly not sure they're doing much.",
  bucket:"the communication, the planning ideas, or the coordination with your CPA and attorney",
  buckets:["communication","proactive ideas","coordination with your other people","performance"],
  truth:"Two years without a review meeting and a rollover still sitting in cash.",
  seeds:["two years with no review meeting","your advisor's junior person now runs the relationship",
         "a rollover that sat in cash for a year","the firm was acquired and nobody called"],
  cue:"That's the part that bugs me. I'm always the one calling him.",
  jump:"how your firm is different, or a second opinion on the portfolio",
  traps:["Are you with one of the big firms or independent?","What do you charge?","How'd you do last year versus the S and P?"]},

 {id:"taxes", family:"A tax bill that arrived without warning",
  say:"Taxes have been brutal the last couple of years.",
  bucket:"business income, investment income, real estate, or a one-time event",
  buckets:["business income","investment income","real estate","a one-time event"],
  truth:"You wrote a large check in April with no warning and felt stupid about it.",
  seeds:["an April surprise nobody flagged","a K-1 that showed up in September",
         "an estimated payment schedule that no longer matches the business","depreciation running out on a property"],
  cue:"That's exactly what happens. I find out in April.",
  jump:"tax-efficient investing, municipal bonds, or a tax plan",
  traps:["My CPA handles all that.","So how do you actually get around that?","Are you a CPA?"]},

 {id:"sale", family:"A sale or exit that may be closer than they admit",
  say:"I might sell the company in the next couple of years.",
  bucket:"still a possibility, or are conversations already happening",
  buckets:["the tax side","what happens to the proceeds","what you'd do afterward","whether now is the right time"],
  truth:"A banker gave you an indication of value eleven weeks ago and you have told almost nobody.",
  seeds:["an unsolicited indication of value from a banker","a competitor who just sold and told you the number",
         "a partner who wants out first","kids who have made clear they do not want it"],
  cue:"Yeah — I hadn't really thought about the before part.",
  jump:"investing the proceeds or a QSBS/1202 strategy",
  traps:["What would you do with that kind of number?","Do you know any good M and A guys?","What's this going to cost me?"]},

 {id:"rollup", family:"A private equity roll-up circling their practice",
  say:"These PE groups keep calling about the practices. Everybody's selling.",
  bucket:"whether you'd actually sell, or what happens to you afterward",
  buckets:["the number","what happens to you after","the rollover equity","whether you'd still be working for them"],
  truth:"You have taken two of those calls and not told your partner.",
  seeds:["two calls you took and did not mention to your partner","a colleague down the street who just closed one",
         "a term sheet sitting unopened in a drawer","a partner who wants to take the first offer"],
  cue:"That's the part nobody explains. What happens to me after.",
  jump:"rollover equity structures, QSBS, or an installment sale",
  traps:["What are these things going for?","Should I take it?","Do you know the group that's buying up practices down here?"]},

 {id:"stock", family:"Concentration in one position or one asset",
  say:"Too much of my net worth is in one thing, and I know it.",
  bucket:"the tax hit, the restrictions on when you can sell, or just never getting around to it",
  buckets:["taxes","trading restrictions","timing","not having a rule"],
  truth:"Somebody at your level was let go in January holding all of it.",
  seeds:["a peer laid off holding everything","a vesting tranche that just doubled the concentration",
         "a lockup that finally came off","a stock that has gone sideways for two years"],
  cue:"Right. I just never actually decide.",
  jump:"a 10b5-1 plan, an exchange fund, or collars",
  traps:["Where do you think the stock's going?","Should I just sell it all?","What are the taxes on that?"]},

 {id:"estate", family:"Estate documents that no longer match reality",
  say:"We really need to update our estate plan.",
  bucket:"the documents themselves, or whether they still match what you actually own",
  buckets:["the documents","the titling","taxes","family changes"],
  truth:"Your daughter asked you a question at Thanksgiving you could not answer.",
  seeds:["a question from an adult child you could not answer","documents drawn up in another state years ago",
         "a second marriage the documents never accounted for","a parent's estate that went badly"],
  cue:"Huh. I honestly don't know if that was ever done.",
  jump:"trusts, gifting strategies, or an attorney referral",
  traps:["Do you have an attorney you like?","What does a trust cost?","Isn't the exemption going away?"]},

 {id:"retire", family:"Not knowing when, or whether, they can stop",
  say:"I'm not really sure when I can retire, or if I can.",
  bucket:"having enough, replacing the income, or getting the value out of the business",
  buckets:["having enough","replacing income","the business","taxes and healthcare"],
  truth:"Your back went out in February and you could not work for three weeks.",
  seeds:["three weeks you could not work and the business felt it","a friend the same age who just stopped",
         "a spouse who has already picked a date","a number somebody quoted you that sounded impossible"],
  cue:"That's the whole thing, isn't it. It's all the business.",
  jump:"a retirement plan, an annuity, or running a projection",
  traps:["What's the number I need?","Can I retire or not?","How much do people like me usually have?"]},

 {id:"kids", family:"Helping adult children without damaging them",
  say:"We want to help the kids, but I don't want to wreck them either.",
  bucket:"the tax side, keeping it fair between them, or the behavior side",
  buckets:["taxes","fairness","control","timing"],
  truth:"One child has been quietly supported for years and the others do not know.",
  seeds:["one child quietly supported and the others unaware","a down payment request you have not answered",
         "a son-in-law you do not trust","a spouse who disagrees with you about how much"],
  cue:"Yeah. And my wife and I aren't totally on the same page.",
  jump:"529s, trusts, or gifting limits",
  traps:["How much can I give them without the tax?","What would you do?","Would you tell them or not?"]},

 {id:"property", family:"Real estate concentration or a property just sold",
  say:"We just sold a building, so there's cash sitting there now.",
  bucket:"replacing the income, buying another one, or diversifying out of real estate",
  buckets:["taxes on the sale","replacing income","buying again","diversifying"],
  truth:"The 1031 identification window closes in nineteen days and nobody has told you.",
  seeds:["a 1031 window nobody warned you about","special assessments on three condo units at once",
         "insurance that tripled and killed the yield","a tenant that just left a building empty"],
  cue:"That's fair. I've kind of been sitting on it.",
  jump:"a 1031, a DST, or an income portfolio",
  traps:["Should I buy another building?","You think Miami real estate holds up?","What do you think about the condo market right now?"]},

 {id:"inherit", family:"Money arriving from a parent or a family estate",
  say:"My mother passed last year, and there's money coming that I haven't dealt with.",
  bucket:"the tax and account side, or how it sits between you and your siblings",
  buckets:["the tax side","the accounts themselves","siblings","what it changes for you"],
  truth:"The account is still in your late mother's name and your brother is the co-executor.",
  seeds:["accounts still titled in a parent's name","a sibling who is co-executor and unreachable",
         "an inherited IRA with a ten-year clock running","a house nobody wants to be the one to sell"],
  cue:"Right, and nobody's telling us what the clock is.",
  jump:"an inherited IRA, a step-up, or a trust",
  traps:["Do we have to sell the house?","How long do we have?","My brother's handling it, why would I need you?"]},

 {id:"latam", family:"Family money crossing into the US",
  say:"Part of the family's money is still outside the country, and it's complicated.",
  bucket:"the reporting side, the currency side, or where the family actually wants to end up",
  buckets:["reporting and compliance","currency","where the family lives","what stays there"],
  truth:"Your sister moved to Madrid and the family structure no longer works for everyone.",
  seeds:["a sibling who moved and broke the structure","a bank abroad that started asking new questions",
         "children who are now US citizens and the parents are not","a country risk conversation the family keeps avoiding"],
  cue:"Exactly. Every person tells us something different.",
  jump:"trusts, PFICs, or a specific reporting form",
  traps:["Do you handle international?","Is that even legal?","Our attorney in Bogota handles it."]},

 {id:"busy", family:"Knows what to do and never gets to it",
  say:"I know I need to deal with this stuff. I'm just always slammed.",
  bucket:"actually a time problem, or nobody's made the decisions clear enough",
  buckets:["time","clarity","not knowing who to ask","it never feels urgent"],
  truth:"An unsigned trust document has been on your desk for fourteen months.",
  seeds:["an unsigned document sitting for over a year","three advisors who all want a meeting and none of them coordinate",
         "a to-do list your spouse now asks about","a folder you moved from one desk to another"],
  cue:"That's it exactly. It just never gets to the top.",
  jump:"how easy your process is, or an onboarding call",
  traps:["How long does this take?","I don't have time for a big process.","Can't you just do it?"]},

 {id:"business_all", family:"Everything is inside the business",
  say:"Pretty much everything I've got is tied up in the business.",
  bucket:"by design, or it just grew that way",
  buckets:["risk","liquidity","retirement","what happens if you stop"],
  truth:"One customer is 40% of revenue and renegotiates next quarter.",
  seeds:["one customer who is most of the revenue","a line of credit personally guaranteed",
         "a building the business owns and you personally financed","a key employee who could leave and take accounts"],
  cue:"Yeah, that's exactly the situation.",
  jump:"diversifying, or building assets outside the business",
  traps:["How much should I be pulling out?","Business is good though, why would I change it?","What do other owners do?"]}
];

/* Phrases that end a run badly. Checked client-side, instantly. */
const BANNED=[
 [/\bI'?d love to (help|work with|chat|connect)\b/i,"I'd love to help"],
 [/\bI'?d be happy to\b/i,"I'd be happy to"],
 [/\bwe can (help|definitely help|do that|handle|take care)\b/i,"We can help with that"],
 [/\bthat'?s (exactly )?what we do\b/i,"That's what we do"],
 [/\byou should (consider|think about|look at|do|get|buy|start|set up|be|have|talk|move|put)\b/i,"You should…"],
 [/\byou (really )?need (a|an|to|some|the)\b/i,"You need…"],
 [/\byou ought to\b|\byou'?d want to\b|\bwhat you want to do is\b/i,"You ought to…"],
 [/\bI(’|')?d (recommend|suggest|advise)\b|\bI would (recommend|suggest|advise)\b/i,"I'd recommend…"],
 [/\bmy (advice|recommendation) (is|would be)\b/i,"My advice is…"],
 [/\bwhat we do is\b|\blet me tell you (about )?what we do\b/i,"Let me tell you what we do"],
 [/\bour (firm|process|team|approach|practice) (is|does|has|works)\b/i,"Explaining your firm"],
 [/\bwe (manage|have|oversee|run|handle) (over |about |roughly |north of |around )?(\$|\d+\s?(million|billion|mm|bn))/i,"AUM drop"],
 [/\b\$?\d+(\.\d+)?\s?(million|billion)\s+(in assets|under management|of assets)\b/i,"AUM drop"],
 [/\bcan I send you\b|\bsend you (some )?(information|materials|a deck|something on)\b/i,"Can I send you information"],
 [/\bpick your brain\b/i,"Pick your brain"],
 [/\bhere'?s my card\b|\btake my card\b/i,"Here's my card"],
 [/\bfiduciary\b|\bfee[- ]only\b|\bassets under management\b/i,"Credential drop"],
 [/\b401\s?\(?k\)?\b|\bannuit(y|ies)\b|\bdonor[- ]advised\b|\bDAF\b|\bmuni(cipal)? bonds?\b|\btreasur(y|ies)\b|\bT[- ]bills?\b|\bindex funds?\b|\bmutual funds?\b|\bETFs?\b|\bRoth\b|\bIRA\b|\bSEP\b|\bcash balance\b|\bdefined benefit\b|\b529\b|\b1031\b|\bDST\b|\b10b5-?1\b|\bQSBS\b|\b1202\b|\bexchange fund\b|\bcollar\b|\bstructured note\b|\bprivate credit\b|\bSMA\b|\bPPLI\b|\blife insurance\b|\bwhole life\b|\bcaptive\b|\bopportunity zone\b|\bCRT\b|\bCRUT\b|\bGRAT\b|\bILIT\b|\binstallment sale\b|\bbackdoor\b|\bstep[- ]up in basis\b/i,"Named a product"]
];
const WHYNOW=[/what made (that|this|it|you)/i,/why (is )?(that|this|it) (coming up|surfacing|on your mind)/i,
 /what('s| is) (driving|behind|going on with) (that|this|it)/i,/what (prompted|triggered|got you|started)/i,
 /why now\b/i,/what changed/i,/what happened\b/i,/what('s| is) going on\b/i,
 /how (did|'d) (that|this|it) come up/i,/what'?s got you (thinking|looking)/i,
 /(is|was) there something that\b/i,/what brought (that|this|it) up/i,/why (are|is) (you|that) thinking about (it|that|this) now/i];
const BUCKETQ=[/business.{0,16}personal/i,/personal.{0,16}business/i,/\bor both\b/i,
 /is (that|this|it) more about/i,/is (that|this|it) mostly/i,/is (that|this|it) (a|the) .{0,20}(thing|side|piece|problem)/i,
 /\b(company|business)'?s? money or (your|yours)/i,/which (one|of those|piece|part)/i,
 /\bwhich (bit|side) (of (that|it|this) )?(is|matters|keeps)/i,
 /\bor (just )?getting organi/i,/\bor is it more\b/i,/what part of (that|it|this)/i,
 /taxes,? .*(risk|liquidity|retirement|organi)/i];
const BRIDGE=[/\bcoffee\b/i,/\bcafecito\b/i,/\bcolada\b/i,/\blunch\b/i,/\bbreakfast\b/i,/\bcompare notes\b/i,
 /\bgrab (a |some )?(coffee|drink|bite|breakfast|lunch)\b/i,/\bbuy you (a|some)\b/i,
 /\bsit down\b/i,/\breal conversation\b/i,/\bproper conversation\b/i,/\boff the (sideline|dock|course|tee)\b/i,
 /\bcome by (the|my) office\b/i,/\bstop by (the|my) office\b/i,/\bget (together|on the calendar)\b/i,
 /\btwenty minutes\b/i,/\b20 minutes\b/i,/\bhalf an hour\b/i,/\bthirty minutes\b/i,/\b30 minutes\b/i,
 /\bkeep (talking|going) (about )?(this|that) somewhere\b/i,/\bcontinue this\b/i,/\bpick this up\b/i];
const CAPTURE=[/best (number|way to reach|way to find|email|way to get)/i,/what'?s your (number|cell|email)/i,
 /\bshoot you a text\b/i,/\btext you\b/i,/\bcalendar\b/i,/\bhow do I (get (a )?hold of|reach|find) you\b/i,
 /\bput your (number|info|cell)\b/i,/\bswap numbers\b/i,/\bgive me your (number|cell|email|info)\b/i,
 /\bwhat does (next week|your week|this week) look like\b/i,/\bare you around (next|this)\b/i,
 /\b(monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b/i,/\bI'?ll call you\b/i,
 /\bgrab your (number|info|contact)\b/i,/\bget you on (my|the) calendar\b/i,/\bsend you an invite\b/i];

/* Whole-utterance voice commands, checked before anything is sent to the prospect. */
const COMMANDS=[
 [/^(again|same one|run it again|same (setup|scenario) again|replay|do (that|it) again)\.?$/i,"again"],
 [/^(next|next one|skip|new one|another one|move on)\.?$/i,"next"],
 [/^(repeat|say that again|come again|what|what did (you|they) say|one more time)\??\.?$/i,"repeat"],
 [/^(stop|end|quit|end (the )?session|done|that'?s it|exit)\.?$/i,"stop"],
 [/^(score|score it|score it now|how('?d| did) I do)\??\.?$/i,"score"]
];
